version: "3"

services:
    touchpay-web:
        container_name: touchpay-web
        build:
            context: .
            dockerfile: ./touchpay-web/Dockerfile
            args:
                docroot: /var/www/html
                appname: TouchPay.standard
        restart: always
        tty: true
        volumes:
            - ./touchpay-web:/touchpay-web:delegated
            - ./TouchPay.standard:/var/www/html/TouchPay.standard:delegated
            - ./touchpay-manual/site:/var/www/html/TouchPay.standard/app/webroot/manual:delegated
        ports:
            - 80:80
        environment:
            DEBUG_LEVEL: 2
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: dining_standard
            MYSQL_PASSWORD: dining_standard
            AWS_S3_BUCKET: tpay2-test-bucket
            AWS_S3_REGION: ap-northeast-1
            AWS_S3_KEY: minio
            AWS_S3_SECRET: minio123
            AWS_S3_ENDPOINT: http://minio:9000
            BUILD_MODE: develop
        links:
            - minio:minio
        depends_on:
            - touchpay-mysql

    touchpay-mysql:
        container_name: touchpay-mysql
        build:
            context: .
            dockerfile: ./touchpay-mysql/Dockerfile
        environment:
            MYSQL_DATABASE: standard_tpay
            MYSQL_USER: dining_standard
            MYSQL_PASSWORD: dining_standard
            MYSQL_ROOT_PASSWORD: password
            TZ: Asia/Tokyo
        volumes:
            - ./touchpay-mysql/sqls/init.sql:/docker-entrypoint-initdb.d/init.sql:delegated
            - ./db/mysql_data:/var/lib/mysql:delegated
        ports:
            - 3306:3306

    minio:
        image: minio/minio:RELEASE.2021-09-23T04-46-24Z
        container_name: "minio"
        ports:
            - 9090:9000
            - 9091:9091
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio123
        entrypoint: sh
        command: -c "mkdir -p /data/.minio.sys/buckets;cp -r /policies/* /data/.minio.sys/;cp -r /export/* /data/;minio server /data --console-address ":9091";"
        volumes:
            - ./minio/data:/data
            - ./minio/export:/export
            - ./minio/config:/root/.minio
            - ./minio/policies:/policies
