version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/TouchPay.standard
hooks:
  AfterInstall:
    - location: deploy-scripts/after_install.sh
      timeout: 300
      runas: root
