# This is a basic workflow to help you get started with Actions

name: Demosite-Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    workflow_dispatch:
        branches: [develop]
    push:
        branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    demosite-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'

            # Python Set up
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.TPAY_DEPLOY_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.TPAY_DEPLOY_SECRET_ACCESS_KEY }}
                aws-region: ap-northeast-1

            # dependencies install
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mkdocs
                  pip install mkdocs-material

            # Manualのビルド
            - name: Manual build
              run: |
                  mkdocs build -f touchpay-manual/mkdocs.yml
                  rm -rf TouchPay.standard/app/webroot/manual
                  cp -pfa touchpay-manual/site TouchPay.standard/app/webroot/manual

            # タブレット画面のビルド
            - name: tablet build
              if: ${{ env.TABLET_ACTIVATE == 'on' }}
              run: |
                  yarn --cwd tablet-touchpay
                  yarn --cwd tablet-touchpay build

            # 個人画面のビルド
            - name: user build
              if: ${{ env.USER_ACTIVATE == 'on'}}
              run: |
                  yarn --cwd user-touchpay
                  yarn --cwd user-touchpay build

            # 厨房画面のビルド
            - name: forkitchen build
              if: ${{ env.FORKITCHEN_ACTIVATE == 'on'}}
              run: |
                  yarn --cwd forkitchen-touchpay
                  yarn --cwd forkitchen-touchpay build

            # 設定ファイルのインポート
            - name: import deploy config file
              run: |
                aws s3 cp s3://tpay2-demo-bucket/artifacts/config/app_$ROOTAPP.php TouchPay.standard/app/config/app_local.php

            # TouchPay.standardの名前変更(名前がかぶるのでtouchpay-packageのみ実行させない)
            - name: rename package
              if: ${{ env.ROOTAPP != 'TouchPay.standard'}}
              run: |
                  mv TouchPay.standard $ROOTAPP


            # TouchPay.standardを圧縮
            - name: archive package
              run: |
                tar zcvf $ROOTAPP.tgz $ROOTAPP

            # s3 upload
            - name: s3 upload
              run: |
                aws s3 cp $ROOTAPP.tgz s3://tpay2-demo-bucket/artifacts/
                aws s3 cp touchpay-mysql/sqls/init.sql s3://tpay2-demo-bucket/artifacts/config/init_$ROOTAPP.sql

            # デプロイメント作成
            - name: create deployment
              run: aws deploy create-deployment --cli-input-json file://.github/workflows/assets/demo-deployment.json

        env:
            WORKDIR: /home/ec2-user/release/${{ secrets.DIRECTORY_NAME }}
            ROOTAPP: ${{ secrets.DIRECTORY_NAME }}
            ROOTDIR: /var/www/html
            TABLET_ACTIVATE: "on"
            USER_ACTIVATE: "on"
            FORKITCHEN_ACTIVATE: "on"
